// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto6.Context;

namespace Projeto6.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220207204126_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projeto6.Models.TbBairro", b =>
                {
                    b.Property<int>("CodigoBairro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_BAIRRO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoMunicipio")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_MUNICIPIO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NOME");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.HasKey("CodigoBairro");

                    b.HasIndex("CodigoMunicipio");

                    b.ToTable("TB_BAIRRO");
                });

            modelBuilder.Entity("Projeto6.Models.TbEndereco", b =>
                {
                    b.Property<int>("CodigoEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_ENDERECO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cep")
                        .HasColumnType("int")
                        .HasColumnName("CEP");

                    b.Property<int>("CodigoBairro")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_BAIRRO");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("COMPLEMENTO");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("NUMERO");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RUA");

                    b.HasKey("CodigoEndereco");

                    b.HasIndex("CodigoBairro");

                    b.ToTable("TB_ENDERECO");
                });

            modelBuilder.Entity("Projeto6.Models.TbMunicipio", b =>
                {
                    b.Property<int>("CodigoMunicipio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_MUNICIPIO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoUf")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_UF");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOME");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.HasKey("CodigoMunicipio");

                    b.HasIndex("CodigoUf");

                    b.ToTable("TB_MUNICIPIO");
                });

            modelBuilder.Entity("Projeto6.Models.TbPessoa", b =>
                {
                    b.Property<int>("CodigoPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_PESSOA")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Idade")
                        .HasColumnType("int")
                        .HasColumnName("IDADE");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LOGIN");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SOBRENOME");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.HasKey("CodigoPessoa");

                    b.ToTable("TB_PESSOA");
                });

            modelBuilder.Entity("Projeto6.Models.TbUf", b =>
                {
                    b.Property<int>("CodigoUf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_UF")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NOME");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("SIGLA");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.HasKey("CodigoUf");

                    b.ToTable("TB_UF");
                });

            modelBuilder.Entity("TbEnderecoTbPessoa", b =>
                {
                    b.Property<int>("TbEnderecoCodigoEndereco")
                        .HasColumnType("int");

                    b.Property<int>("TbPessoaCodigoPessoa")
                        .HasColumnType("int");

                    b.HasKey("TbEnderecoCodigoEndereco", "TbPessoaCodigoPessoa");

                    b.HasIndex("TbPessoaCodigoPessoa");

                    b.ToTable("TbEnderecoTbPessoa");
                });

            modelBuilder.Entity("Projeto6.Models.TbBairro", b =>
                {
                    b.HasOne("Projeto6.Models.TbMunicipio", "TbMunicipio")
                        .WithMany("TbBairros")
                        .HasForeignKey("CodigoMunicipio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TbMunicipio");
                });

            modelBuilder.Entity("Projeto6.Models.TbEndereco", b =>
                {
                    b.HasOne("Projeto6.Models.TbBairro", "TbBairro")
                        .WithMany("TbEndereco")
                        .HasForeignKey("CodigoBairro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TbBairro");
                });

            modelBuilder.Entity("Projeto6.Models.TbMunicipio", b =>
                {
                    b.HasOne("Projeto6.Models.TbUf", "TbUf")
                        .WithMany("TbMunicipio")
                        .HasForeignKey("CodigoUf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TbUf");
                });

            modelBuilder.Entity("TbEnderecoTbPessoa", b =>
                {
                    b.HasOne("Projeto6.Models.TbEndereco", null)
                        .WithMany()
                        .HasForeignKey("TbEnderecoCodigoEndereco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto6.Models.TbPessoa", null)
                        .WithMany()
                        .HasForeignKey("TbPessoaCodigoPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Projeto6.Models.TbBairro", b =>
                {
                    b.Navigation("TbEndereco");
                });

            modelBuilder.Entity("Projeto6.Models.TbMunicipio", b =>
                {
                    b.Navigation("TbBairros");
                });

            modelBuilder.Entity("Projeto6.Models.TbUf", b =>
                {
                    b.Navigation("TbMunicipio");
                });
#pragma warning restore 612, 618
        }
    }
}
